### ISSUE TITLE
Error in fbtft_device.c when attempting compile with 3.18.y kernel

### ISSUE THREAD

**Issue by harrisclinton** [xobs/adafruit-rpi-fbtft#1]
I received the following error from fbtft_device.c when attempting to compile with 3.18.y kernel sources.

`drivers/video/adafruit-rpi-fbtft/fbtft_device.c:330:5: error: unknown field ‘irq_base’ specified in initializer
make[3]: *** [drivers/video/adafruit-rpi-fbtft/fbtft_device.o] Error 1`

The current stable version of Raspbian, incidentally, uses kernel 3.18 (installing the precompiled patched kernel binaries provided by Adafruit for this tft series rolls the kernel back to 3.12, so compiling from source seems to be a requirement for all new users unless I am missing something - the old kernel breaks some USB performance that I need).
